# Generated by Django 5.0.6 on 2024-11-06 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generals', '0002_logomotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='logomotion',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
