# Generated by Django 5.0.6 on 2024-07-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='rank',
            field=models.IntegerField(default=1, verbose_name='Rank'),
        ),
    ]
