# Generated by Django 5.0.6 on 2024-11-06 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_teammember_link_teammember_dribbble_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='avatar',
            field=models.ImageField(upload_to='multimedias/team_members/', verbose_name='Avatar'),
        ),
    ]
