# Generated by Django 5.0.6 on 2024-11-06 06:00

from django.db import migrations
import os

def update_avatar_paths(apps, schema_editor):
    TeamMember = apps.get_model('accounts', 'TeamMember')
    for member in TeamMember.objects.all():
        if member.avatar:
            # Assuming the new path is 'new_directory/team_members/'
            old_path = member.avatar.name
            new_path = old_path.replace('mutlimedias/team_members/', 'multimedias/team_members/')
            if os.path.exists(os.path.join('media', old_path)):  # Adjust 'media' as per your settings
                os.rename(os.path.join('media', old_path), os.path.join('media', new_path))
                member.avatar.name = new_path
                member.save()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_teammember_avatar'),
    ]

    operations = [
        migrations.RunPython(update_avatar_paths),
    ]
