# Generated by Django 5.0.6 on 2024-07-08 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Title')),
                ('slug', models.SlugField(allow_unicode=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Description')),
                ('cover_image', models.ImageField(upload_to='solutions/cover_images/', verbose_name='Cover image')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='solutions/thumbnails/')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solutions', to='solutions.solutioncategory', verbose_name='Category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
