# Generated by Django 5.0.6 on 2024-07-08 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('solutions', '0002_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solutions', to='clients.client', verbose_name='Client'),
        ),
    ]
