# Generated by Django 5.0.6 on 2024-07-26 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0003_solution_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('year', models.PositiveSmallIntegerField(default=2024)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image', models.ImageField(upload_to='awards/', verbose_name='Image')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
