# Generated by Django 5.0.6 on 2024-11-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0005_solution_active_solution_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='design_date',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Design date'),
        ),
        migrations.AddField(
            model_name='solution',
            name='designer',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Designer'),
        ),
        migrations.AddField(
            model_name='solution',
            name='manufacturing_methods',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Manufacturing methods'),
        ),
        migrations.AddField(
            model_name='solution',
            name='product_model',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Product model'),
        ),
    ]
