# Generated by Django 5.0.6 on 2024-07-26 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solutions', '0003_solution_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('file', models.ImageField(upload_to='multimedias/images/', verbose_name='File')),
                ('image_alt', models.CharField(default='', max_length=150, verbose_name='Image alt')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='multimedias/images/thumbnails/', verbose_name='Thumbnail')),
                ('solution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='solutions.solution', verbose_name='Solution')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
