# Generated by Django 5.0.6 on 2024-07-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_alt',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Image alt'),
        ),
    ]
