# Generated by Django 5.0.6 on 2024-07-26 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedias', '0003_image_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='image',
            name='zone',
            field=models.CharField(choices=[('solution', 'Solution'), ('about', 'About')], default='solution', max_length=10, verbose_name='Zone'),
        ),
        migrations.AddField(
            model_name='image',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='multimedias.gallery', verbose_name='Gallery'),
        ),
    ]
